# Generated by Django 6.1.1 on 2026-10-08 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquinaria',
            name='imagen_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
