# Generated by Django 6.1.1 on 2026-10-08 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_maquinaria_imagen_url'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='itemcarro',
            constraint=models.UniqueConstraint(fields=('carro', 'maquinaria', 'fecha_inicio', 'fecha_fin'), name='item_carro_unico_por_periodo'),
        ),
    ]
